name: Test and Check Zip Content

on:
  workflow_dispatch:

jobs:
  check-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Unzip application
      run: |
        unzip my_digital_wallet.zip -d test_folder
        
    - name: List all files inside zip
      run: |
        echo "=== الملفات الموجودة داخل الـ Zip هي ==="
        find test_folder
